# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ttntmeZpqY.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1539, 896)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 771, 51))
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 70, 311, 61))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_2.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(340, 70, 311, 61))
        self.label_3.setFont(font1)
        self.label_3.setLayoutDirection(Qt.RightToLeft)
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(720, 10, 821, 51))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(720, 60, 821, 31))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setWeight(75)
        self.label_5.setFont(font2)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 150, 641, 91))
        font3 = QFont()
        font3.setPointSize(10)
        self.groupBox.setFont(font3)
        self.splitter_6 = QSplitter(self.groupBox)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setGeometry(QRect(10, 30, 621, 51))
        self.splitter_6.setOrientation(Qt.Horizontal)
        self.yoloPath = QPlainTextEdit(self.splitter_6)
        self.yoloPath.setObjectName(u"yoloPath")
        self.splitter_6.addWidget(self.yoloPath)
        self.initButton = QPushButton(self.splitter_6)
        self.initButton.setObjectName(u"initButton")
        self.splitter_6.addWidget(self.initButton)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(680, 150, 851, 441))
        self.groupBox_2.setFont(font3)
        self.imgOut = QLabel(self.groupBox_2)
        self.imgOut.setObjectName(u"imgOut")
        self.imgOut.setGeometry(QRect(10, 30, 821, 401))
        self.logView = QListWidget(self.centralwidget)
        self.logView.setObjectName(u"logView")
        self.logView.setGeometry(QRect(20, 250, 641, 221))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 480, 641, 351))
        self.groupBox_3.setFont(font3)
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 171, 29))
        self.packageAvailable = QPlainTextEdit(self.groupBox_3)
        self.packageAvailable.setObjectName(u"packageAvailable")
        self.packageAvailable.setGeometry(QRect(190, 30, 51, 31))
        self.packageAvailable.setAcceptDrops(False)
        self.packageAvailable.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.packageAvailable.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.packageAvailable.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 70, 160, 31))
        self.packagePacked = QPlainTextEdit(self.groupBox_3)
        self.packagePacked.setObjectName(u"packagePacked")
        self.packagePacked.setGeometry(QRect(190, 70, 51, 31))
        self.packagePacked.setAcceptDrops(False)
        self.packagePacked.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.packagePacked.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.packagePacked.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.speed = QDial(self.groupBox_3)
        self.speed.setObjectName(u"speed")
        self.speed.setGeometry(QRect(250, 30, 101, 81))
        self.speed.setMaximum(100)
        self.speed.setWrapping(False)
        self.speed.setNotchesVisible(True)
        self.label_24 = QLabel(self.groupBox_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 110, 231, 41))
        self.beginButton = QPushButton(self.groupBox_3)
        self.beginButton.setObjectName(u"beginButton")
        self.beginButton.setGeometry(QRect(260, 260, 361, 61))
        self.splitter_16 = QSplitter(self.groupBox_3)
        self.splitter_16.setObjectName(u"splitter_16")
        self.splitter_16.setGeometry(QRect(10, 270, 231, 61))
        self.splitter_16.setOrientation(Qt.Vertical)
        self.label_28 = QLabel(self.splitter_16)
        self.label_28.setObjectName(u"label_28")
        self.splitter_16.addWidget(self.label_28)
        self.splitter_13 = QSplitter(self.splitter_16)
        self.splitter_13.setObjectName(u"splitter_13")
        self.splitter_13.setOrientation(Qt.Horizontal)
        self.label_29 = QLabel(self.splitter_13)
        self.label_29.setObjectName(u"label_29")
        font4 = QFont()
        font4.setPointSize(12)
        self.label_29.setFont(font4)
        self.splitter_13.addWidget(self.label_29)
        self.boxWidth = QPlainTextEdit(self.splitter_13)
        self.boxWidth.setObjectName(u"boxWidth")
        self.boxWidth.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_13.addWidget(self.boxWidth)
        self.label_30 = QLabel(self.splitter_13)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setFont(font4)
        self.splitter_13.addWidget(self.label_30)
        self.boxHeight = QPlainTextEdit(self.splitter_13)
        self.boxHeight.setObjectName(u"boxHeight")
        self.boxHeight.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_13.addWidget(self.boxHeight)
        self.splitter_16.addWidget(self.splitter_13)
        self.splitter_8 = QSplitter(self.groupBox_3)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setGeometry(QRect(350, 30, 271, 71))
        self.splitter_8.setOrientation(Qt.Vertical)
        self.label_21 = QLabel(self.splitter_8)
        self.label_21.setObjectName(u"label_21")
        self.splitter_8.addWidget(self.label_21)
        self.progressBar = QProgressBar(self.splitter_8)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setValue(19)
        self.splitter_8.addWidget(self.progressBar)
        self.splitter_9 = QSplitter(self.groupBox_3)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setGeometry(QRect(260, 120, 361, 51))
        self.splitter_9.setOrientation(Qt.Horizontal)
        self.clearErrorbutton = QPushButton(self.splitter_9)
        self.clearErrorbutton.setObjectName(u"clearErrorbutton")
        self.splitter_9.addWidget(self.clearErrorbutton)
        self.checkPickupPos = QPushButton(self.splitter_9)
        self.checkPickupPos.setObjectName(u"checkPickupPos")
        self.splitter_9.addWidget(self.checkPickupPos)
        self.checkDropPos = QPushButton(self.splitter_9)
        self.checkDropPos.setObjectName(u"checkDropPos")
        self.splitter_9.addWidget(self.checkDropPos)
        self.splitter_10 = QSplitter(self.groupBox_3)
        self.splitter_10.setObjectName(u"splitter_10")
        self.splitter_10.setGeometry(QRect(260, 190, 361, 61))
        self.splitter_10.setOrientation(Qt.Horizontal)
        self.zeroPos = QPushButton(self.splitter_10)
        self.zeroPos.setObjectName(u"zeroPos")
        self.splitter_10.addWidget(self.zeroPos)
        self.palletView = QPushButton(self.splitter_10)
        self.palletView.setObjectName(u"palletView")
        self.splitter_10.addWidget(self.palletView)
        self.splitter_11 = QSplitter(self.groupBox_3)
        self.splitter_11.setObjectName(u"splitter_11")
        self.splitter_11.setGeometry(QRect(10, 150, 231, 41))
        self.splitter_11.setOrientation(Qt.Horizontal)
        self.colIndex = QSpinBox(self.splitter_11)
        self.colIndex.setObjectName(u"colIndex")
        self.colIndex.setEnabled(True)
        self.colIndex.setMaximum(2)
        self.splitter_11.addWidget(self.colIndex)
        self.rowIndex = QSpinBox(self.splitter_11)
        self.rowIndex.setObjectName(u"rowIndex")
        self.rowIndex.setMaximum(4)
        self.splitter_11.addWidget(self.rowIndex)
        self.splitter_14 = QSplitter(self.groupBox_3)
        self.splitter_14.setObjectName(u"splitter_14")
        self.splitter_14.setGeometry(QRect(10, 200, 231, 61))
        self.splitter_14.setOrientation(Qt.Vertical)
        self.label_25 = QLabel(self.splitter_14)
        self.label_25.setObjectName(u"label_25")
        self.splitter_14.addWidget(self.label_25)
        self.splitter_12 = QSplitter(self.splitter_14)
        self.splitter_12.setObjectName(u"splitter_12")
        self.splitter_12.setOrientation(Qt.Horizontal)
        self.label_27 = QLabel(self.splitter_12)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setFont(font4)
        self.splitter_12.addWidget(self.label_27)
        self.cameraXoffsets = QPlainTextEdit(self.splitter_12)
        self.cameraXoffsets.setObjectName(u"cameraXoffsets")
        self.cameraXoffsets.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_12.addWidget(self.cameraXoffsets)
        self.label_26 = QLabel(self.splitter_12)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setFont(font4)
        self.splitter_12.addWidget(self.label_26)
        self.cameraYoffsets = QPlainTextEdit(self.splitter_12)
        self.cameraYoffsets.setObjectName(u"cameraYoffsets")
        self.cameraYoffsets.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_12.addWidget(self.cameraYoffsets)
        self.splitter_14.addWidget(self.splitter_12)
        self.splitter_5 = QSplitter(self.centralwidget)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setGeometry(QRect(680, 690, 851, 71))
        self.splitter_5.setOrientation(Qt.Horizontal)
        self.groupBox_6 = QGroupBox(self.splitter_5)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setFont(font3)
        self.splitter_3 = QSplitter(self.groupBox_6)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(10, 30, 401, 31))
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.label_15 = QLabel(self.splitter_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setFont(font4)
        self.splitter_3.addWidget(self.label_15)
        self.baseDropX = QPlainTextEdit(self.splitter_3)
        self.baseDropX.setObjectName(u"baseDropX")
        self.baseDropX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_3.addWidget(self.baseDropX)
        self.label_16 = QLabel(self.splitter_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setFont(font4)
        self.splitter_3.addWidget(self.label_16)
        self.baseDropY = QPlainTextEdit(self.splitter_3)
        self.baseDropY.setObjectName(u"baseDropY")
        self.baseDropY.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_3.addWidget(self.baseDropY)
        self.label_17 = QLabel(self.splitter_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setFont(font4)
        self.splitter_3.addWidget(self.label_17)
        self.baseDropZ = QPlainTextEdit(self.splitter_3)
        self.baseDropZ.setObjectName(u"baseDropZ")
        self.baseDropZ.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_3.addWidget(self.baseDropZ)
        self.splitter_5.addWidget(self.groupBox_6)
        self.groupBox_7 = QGroupBox(self.splitter_5)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setFont(font3)
        self.splitter_4 = QSplitter(self.groupBox_7)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(10, 30, 401, 31))
        self.splitter_4.setOrientation(Qt.Horizontal)
        self.label_18 = QLabel(self.splitter_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setFont(font4)
        self.splitter_4.addWidget(self.label_18)
        self.currDropX = QPlainTextEdit(self.splitter_4)
        self.currDropX.setObjectName(u"currDropX")
        self.currDropX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_4.addWidget(self.currDropX)
        self.label_19 = QLabel(self.splitter_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setFont(font4)
        self.splitter_4.addWidget(self.label_19)
        self.currDropY = QPlainTextEdit(self.splitter_4)
        self.currDropY.setObjectName(u"currDropY")
        self.currDropY.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_4.addWidget(self.currDropY)
        self.label_20 = QLabel(self.splitter_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setFont(font4)
        self.splitter_4.addWidget(self.label_20)
        self.currDropZ = QPlainTextEdit(self.splitter_4)
        self.currDropZ.setObjectName(u"currDropZ")
        self.currDropZ.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_4.addWidget(self.currDropZ)
        self.label_23 = QLabel(self.splitter_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setFont(font4)
        self.splitter_4.addWidget(self.label_23)
        self.currDropYaw = QPlainTextEdit(self.splitter_4)
        self.currDropYaw.setObjectName(u"currDropYaw")
        self.currDropYaw.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_4.addWidget(self.currDropYaw)
        self.splitter_5.addWidget(self.groupBox_7)
        self.splitter_7 = QSplitter(self.centralwidget)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setGeometry(QRect(680, 600, 851, 71))
        self.splitter_7.setOrientation(Qt.Horizontal)
        self.groupBox_4 = QGroupBox(self.splitter_7)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setFont(font3)
        self.splitter = QSplitter(self.groupBox_4)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(10, 30, 401, 31))
        self.splitter.setOrientation(Qt.Horizontal)
        self.label_9 = QLabel(self.splitter)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font4)
        self.splitter.addWidget(self.label_9)
        self.palletX = QPlainTextEdit(self.splitter)
        self.palletX.setObjectName(u"palletX")
        self.palletX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter.addWidget(self.palletX)
        self.label_10 = QLabel(self.splitter)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFont(font4)
        self.splitter.addWidget(self.label_10)
        self.palletY = QPlainTextEdit(self.splitter)
        self.palletY.setObjectName(u"palletY")
        self.palletY.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter.addWidget(self.palletY)
        self.label_11 = QLabel(self.splitter)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setFont(font4)
        self.splitter.addWidget(self.label_11)
        self.palletZ = QPlainTextEdit(self.splitter)
        self.palletZ.setObjectName(u"palletZ")
        self.palletZ.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter.addWidget(self.palletZ)
        self.splitter_7.addWidget(self.groupBox_4)
        self.groupBox_5 = QGroupBox(self.splitter_7)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setFont(font3)
        self.splitter_2 = QSplitter(self.groupBox_5)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(10, 30, 401, 31))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.label_12 = QLabel(self.splitter_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setFont(font4)
        self.splitter_2.addWidget(self.label_12)
        self.pickUpX = QPlainTextEdit(self.splitter_2)
        self.pickUpX.setObjectName(u"pickUpX")
        self.pickUpX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_2.addWidget(self.pickUpX)
        self.label_13 = QLabel(self.splitter_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font4)
        self.splitter_2.addWidget(self.label_13)
        self.pickUpY = QPlainTextEdit(self.splitter_2)
        self.pickUpY.setObjectName(u"pickUpY")
        self.pickUpY.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_2.addWidget(self.pickUpY)
        self.label_14 = QLabel(self.splitter_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setFont(font4)
        self.splitter_2.addWidget(self.label_14)
        self.pickUpZ = QPlainTextEdit(self.splitter_2)
        self.pickUpZ.setObjectName(u"pickUpZ")
        self.pickUpZ.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_2.addWidget(self.pickUpZ)
        self.label_22 = QLabel(self.splitter_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setFont(font4)
        self.splitter_2.addWidget(self.label_22)
        self.pickUpYaw = QPlainTextEdit(self.splitter_2)
        self.pickUpYaw.setObjectName(u"pickUpYaw")
        self.pickUpYaw.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter_2.addWidget(self.pickUpYaw)
        self.splitter_7.addWidget(self.groupBox_5)
        self.splitter_15 = QSplitter(self.centralwidget)
        self.splitter_15.setObjectName(u"splitter_15")
        self.splitter_15.setGeometry(QRect(0, 0, 0, 0))
        self.splitter_15.setOrientation(Qt.Vertical)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1539, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.speed.valueChanged.connect(self.progressBar.setValue)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"GIAO DI\u1ec6N \u0110I\u1ec0U KHI\u1ec2N TAY G\u1eaeP H\u00c0NG", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Sinh vi\u00ean: H\u1ed3 \u0110\u1ee9c An 2286300050\n"
"Nguy\u1ec5n V\u0169 Huy Kh\u00f4i 2286300027\n"
"Nguy\u1ec5n Thanh Nh\u00e2n 2286301149", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"GVHD: Th\u1ea7y Ng\u00f4 An Thuy\u00ean\n"
"L\u1edbp: 22DRTA1\n"
"Robot v\u00e0 Tr\u00ed tu\u1ec7 nh\u00e2n t\u1ea1o", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"TR\u01af\u1edcNG \u0110\u1ea0I H\u1eccC C\u00d4NG NGH\u1ec6 TP.HCM HUTECH", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Vi\u1ec7n K\u1ef9 Thu\u1eadt HUTECH", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Kh\u1edfi \u0111\u1ed9ng", None))
        self.yoloPath.setDocumentTitle("")
        self.yoloPath.setPlainText("")
        self.yoloPath.setPlaceholderText(QCoreApplication.translate("MainWindow", u"YOLO path", None))
        self.initButton.setText(QCoreApplication.translate("MainWindow", u"Kh\u1edfi \u0111\u1ed9ng", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.imgOut.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Th\u00f4ng tin", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"S\u1ed1 ki\u1ec7n h\u00e0ng \u0111ang c\u00f3", None))
        self.packageAvailable.setPlainText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"S\u1ed1 ki\u1ec7n h\u00e0ng \u0111\u00e3 g\u1eafp  ", None))
        self.packagePacked.setPlainText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"S\u1ed1 h\u00e0ng/c\u1ed9t", None))
        self.beginButton.setText(QCoreApplication.translate("MainWindow", u"B\u1eaft \u0111\u1ea7u", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Box dimension", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"W:", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"H:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.clearErrorbutton.setText(QCoreApplication.translate("MainWindow", u"Clear Error", None))
        self.checkPickupPos.setText(QCoreApplication.translate("MainWindow", u"Ki\u1ec3m tra\n"
" t\u1ecda \u0111\u1ed9 g\u1eafp", None))
        self.checkDropPos.setText(QCoreApplication.translate("MainWindow", u"Ki\u1ec3m tra\n"
" t\u1ecda \u0111\u1ed9 th\u1ea3", None))
        self.zeroPos.setText(QCoreApplication.translate("MainWindow", u"Zero Position", None))
        self.palletView.setText(QCoreApplication.translate("MainWindow", u"Pallet view", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Camera Offsets", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"T\u1ecda \u0111\u1ed9 th\u1ea3 v\u1eadt g\u1ed1c", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Z:", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"T\u1ecda \u0111\u1ed9 th\u1ea3 v\u1eadt d\u1ef1 ki\u1ebfn", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Z:", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Yaw:", None))
        self.currDropYaw.setPlainText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"T\u1ecda \u0111\u1ed9 pallet", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Z:", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"T\u1ecda \u0111\u1ed9 g\u1eafp", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Z:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Yaw:", None))
        self.pickUpYaw.setPlainText(QCoreApplication.translate("MainWindow", u"0", None))
    # retranslateUi


if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())